[build]
builder = "nixpacks"

[build.env]
NIXPACKS_NODE_VERSION = "18"
NPM_CONFIG_PACKAGE_LOCK = "false"

[deploy]
startCommand = "npm start"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10

# Force npm install instead of npm ci
[[build.phases]]
name = "install"
commands = ["npm install --production"]